### ISSUE TITLE
Feedback: File type filters are overly restrictive

### ISSUE THREAD

**Issue by bradisbell** [WICG/file-system-access#243]
From the explainer:

> Limiting write access to certain file types
> Not allowing websites to write to certain file types such as executables will limit the possible attack surface.

This restriction prevents the implementation of common tools such as file sharing, download managers, web-based IDEs, and many others.  Such restrictions prevent entire classes of applications from being developed, and will continue holding back the web as an application platform.

Users should be free to choose how they use their own filesystem.

Please consider removing this restriction from the spec.

**Comment by kjperkin** [comment]
I agree. The spec should instead require user agents to implement safeguards to prevent certain kinds of files from being written without the user's explicit consent. A conforming implementation might prompt the user to confirm the creation of a file with potentially hazardous characteristics or might require the user to have configured some kind of allowlist in advance.

Another way to do this could be to have some kind of permissions API where a web application may request the ability to create certain kinds of files or files with certain properties and the user is able to review the application's requested capabilities and decide what to do. For example, an application might request the ability to write executable files (with what constitutes "executable" being platform dependent) along with ".txt", ".png", ".bmp", and ".xml" files. The user agent can provide pretty descriptions for well-known capabilities such as these while reverting to a description like ".foo files" for unrecognized extensions.

**Comment by a-sully** [comment]
Checking back in on this issue... the quoted text is from the explainer, but the spec is much more generous https://wicg.github.io/file-system-access/#wellknowndirectory-too-sensitive-or-dangerous. And the spec is ultimately what matters here. In Chromium browsers we have a few other checks which vary in scope depending on the context (there are some files types we block from being selected through the picker, but we allow you to operate on if files of that type exist in a directory you have write access to).

In general, we want to enable applications to build powerful experiences. A sync client should be able to modify an `.exe` file in a directory the user has explicitly granted it permission to sync, for example. But some files types, like `.lnk`, are simply too dangerous to allow on the web.

> have some kind of permissions API where a web application may request the ability to create certain kinds of files or files with certain properties and the user is able to review the application's requested capabilities and decide what to do

Since this issue was filed, we've added an additional dialog to the `showSaveFilePicker()` flow which warns users when they're about to save a file with a potentially dangerous extension. The user must explicitly opt in for the file to be saved
