### ISSUE TITLE
Obtaining the Accessed Path in any way?

### ISSUE THREAD

**Issue by harunoz** [WICG/file-system-access#282]
Hello, can I obtain the accessed path by the website that uses file system access API? For example, after the user choose its directory and grant access to the website, how can I obtain the exact path that reached by the website. I am thinking of using google-chrome-devtools any idea how can I do that?

**Comment by jimmywarting** [comment]
It's not possible due to security design.
All doe it would be nice if chrome had a private field or flag `[[path]]: ` that we could not access from javascript but we could use dev tool to see the path.

a question that popped up in my head is: Would a "Reveal in Finder/Explorer" be a harmless feature to add to this api?

**Comment by mkruisselbrink** [comment]
Exposing the full path in devtools is definitely something we've been thinking about (not sure if we ever got to the point of having a feature request for it filed). I don't see any reason why we couldn't do that.

As said, exposing the full path to the website itself isn't something we're willing to do for privacy/security reasons. Many file paths would for example have the user's name/username in its path, which would reveal more information than we're willing to reveal.

Having a "Reveal in Finder/Explorer" option I think is #156. Seems plausible, not sure about the details. Maybe we could even have a "draw the path of this file to this canvas" operation, which would taint the canvas similarly to how drawing (non-cors) cross origin images does. Although that might be hard to use correctly since we couldn't tell you how much space the path took up either.

**Comment by harunoz** [comment]
Thank you for your answers. I am actually a researcher and I do not aim to get the path as a web application developer. I intend to reach the path using devtools possibly via hooking techniques for research purposes. Also, I have tried to extract the path tracing with devtools and monitoring the activity of the chrome processes.

Do you have any other ideas?

**Comment by Wolsten** [comment]
I don't understand why the full path should not be presented to the user? User working on their own machine will see the full path when they open a file or directory and give permission to view and edit. Yes they could save the full path in a document created by the app which could lead to a potential issue so perhaps the ability to view the retrieve the full path should be an opt-in permission?  A Team Worker might find it restricting not to be able to share a path to their colleagues. A "Reveal in Finder/Explorer" option might be a good option in the meantime.

**Comment by ftreesmilo** [comment]
Not showing the full path to the app makes this really hard to provide a nice integrated UX that a user expects from an application.

There are many user consent interactions around this api...   If the user selects a pass with their username in it, I find it hard to believe that they don't expect to have that read by the application.  I have already gotten feedback from users that they don't remember where they granted access to the folder and they want me to show the full path.

**Comment by ftreesmilo** [comment]
I think I would be fine with extended permissions for installed PWAs, but I really think we need to think about the UX for the user, and not tripping over ourselves to keep any guns the user is running around with pointed away from their toes.

For now I'll try to focus on #156 in hopes it will help them find the folder.   It's not ideal, they want to see the full path in my "app".

**Comment by mkruisselbrink** [comment]
Exposing the full path in devtools is something we definitely should do. https://crbug.com/1059460 is somewhat related, although currently that only talks about handles stored in IndexedDB. I don't see any reason why we wouldn't expose the full path in devtools for all handles though. All of that is more a chromium/implementation issue rather than a spec issue though. As I don't think we'd ever want to expose the full path to javascript I'm closing this issue in favor of chromium implementation bugs, like the one I mentioned.
