### ISSUE TITLE
Feature request: equivalent to path.resolve and path.join relative to a FileSystemDirectoryHandle

### ISSUE THREAD

**Issue by Jarred-Sumner** [WICG/file-system-access#284]
Overall, I think the File System Access API is great for the internet. This is a feature request.

**The ask**: 

An API for normalizing, resolving, and joining file paths relative to a `FileSystemDirectoryHandle` or a `FileSystemFileHandle` **from strings** when the origin has access to the topmost referenced directory. 

API usage example:

Asynchronous (throws `DOMException` if doesn't exist)

- `await directoryHandle.path.resolve("../src/index.js")` => `"/src/index.js"`
- `await directoryHandle.resolve(otherDirectory.path.join("../src/index.js"))` => `FileSystemFileHandle`

Synchronous (does not throw but does not validate/make API calls outside JS):

- `directoryHandle.path.join("../src/index.js")` => `"/src/index.js"`
- `fileHandle.path.join("../public/index.html")` => `"/public/index.html"`

In these examples, its ambiguous what to call the topmost directory handle:
- `/` is incorrect because the top most directory may change if the origin receives access to a parent directory later
- `/:topmost_dir_handle_name` is incorrect if it receives access to a directory two levels above
- `:topmost_dir_handle_name/` as a string could become ambiguous if the origin receives access to a parent directory later

With an approach like this, it probably makes more sense to accept a string as input but to represent relative file paths as a serializable/transferrable String-like object. Maybe a `FileSystemFilePath`. And the `FileSystemFilePath` keeps an internal, inaccessible to the origin reference to its parent `FileSystemDirectoryHandle`? 

**The context**:

I have an autocomplete file picker like this:

https://user-images.githubusercontent.com/709451/111053877-731a8280-841c-11eb-9b77-aadf961efa5c.mp4

It only lists valid file paths, however the file path still needs to be validated afterwards because the user may also manually edit their `package.json` or they may delete the file later.

If you already have the `FileSystemFileHandle`, this seems straightforward. You just call `FileSystemDirectoryHandle.resolve`. However, if you don't have the `FileSystemFileHandle`, but you do have the `FilesystemDirectoryHandle`, you have to write code to walk the tree until it reaches the file/directory or until it no longer exists.

In the simplest case for finding a directory (excluding error handling), the code looks like this 

```ts
    if (!path.isAbsolute(_path) || !_path.startsWith("/")) {
      _path = path.join("/", _path);
    }
    let parts = _path.split("/");
    for (let i = 0; i < parts.length; i++) {
      if (!parts[i]) continue;
      from = await from.getDirectoryHandle(parts[i]);
    }
    return from;

```

Note: `path` here is [`path-browserify`](https://github.com/browserify/path-browserify)

But, I'm sure there are missing edge cases. Most of the logic here is really done by `path-browserify`. 

Many apps that uses the Filesystem Access API for multiple files or accept user input from text will end up needing to implement logic for dealing with file paths and it would be helpful if Filesystem Access API provided built-in abstractions

**Comment by ftreesmilo** [comment]
https://wicg.github.io/file-system-access/#api-filesystemdirectoryhandle-resolve

**Comment by mkruisselbrink** [comment]
I think this kind of splits out in two issues:

- First the question about having some kind of path-based API, rather than having to manually walk the tree. So far the API has intentionally avoided representing paths as strings, to avoid any kind of discussions around path separators, different platforms having different behavior, and in general providing maximum flexibility to map whatever makes sense on the file system to as minimal of an API surface as possible. As such the existing resolve method returns an array of names rather than a single path string, and we don't have any methods to look up a handle by its path. As you show, it's fairly simple to implement a path-based lookup yourself, with whatever path separators etc you want for your specific use case, so I'm not convinced that it is worthwhile adding support for that into the API itself.

- The second question I think is around "../", and being able to access the "parent" directory of some handle. There is a lot more discussion on that problem in general in #193. But the tl;dr. there too I think is that defining what exactly the parent of a handle is is not exactly trivial, and if it is based on "what directories the site has access to" it can change as that access changes, which makes the concept of a parent perhaps somewhat hard to reason about. For the most predictable definition of parent it shouldn't be too hard for a website to polyfill that themselves, so there too I'm not convinced this is something we'd want to add to the API itself.
