### ISSUE TITLE
Provide list of capabilities when requesting access to the entry

### ISSUE THREAD

**Issue by lifaon74** [WICG/file-system-access#33]
The API we all want, thanks for the work !

Personally, I consider that the developer wants to be sure than all the capabilities he needs will be accepted by the user when requesting the access of a file-system (here directory and its sub-directories), to avoid "half done" work (ex: I created a file A, but the user refused to create file B => my app is in an inconsistent state => crash).
Moreover, I would prefer having a full access to a directory + sub-directories (that I will call 'fs'), and be restricted to this area (cannot navigate upper than root defined in an `openFS` function), as opposite to the current api which allow to navigate everywhere and could result in a lot of "prompting" for the user.

This could have the form of:
```js
const fs = await self.openFS({
  path: 'some path', // the user may change the path but the developer should be warned of it (ex: different fs.path)
  capabilities: [ // here's the important point
   'read': // I want read access (for the files)
   'write' // I want write access (for the files)
   'remove', // I want remove access
   'rename', // I want rename access, this includes moving entry too
   // ... open to others capabilities
  ]
}); // fs is RootDirectory
// I can explore the selected root directory and all its children with selected capabilities
// I can't explore entries upper than root (rejected Promise then trying to do this)
```
The browser could prompt a popup showing what the app requires as capabilities (like android or ios) + the option to change path. All capabilities must be accepted at the same time or the promise will fail. The user choice should be cached (to avoid prompting every time) as long as options didn't change, or are less "powerful". Of course the user should be allowed at anytime to delete the fs permissions.

Some API ideas:
```ts
interface FSEntry {
  readonly path: string; // relative to root
  readonly type: 'file' | 'directory';

  parent(): Promise<FSDirectory>; // throws if root directory
  remove(): Promise<void>;
  copy(path: string): Promise<void>;
  move(path: string): Promise<void>;
}

interface FSFile extends FSEntry {
  size(): Promise<number>;
  read(start?: number, end?: number): Promise<void>;
  write(buffer: Blob | ArrayBuffer | string, offset?: number): Promise<void>;
  truncate(size: number): Promise<void>;
}

interface FSDirectory extends FSEntry {
  children(): Promise<string[]>;
}
```

**Comment by mkruisselbrink** [comment]
> Moreover, I would prefer having a full access to a directory + sub-directories (that I will call 'fs'), and be restricted to this area (cannot navigate upper than root defined in an `openFS` function), as opposite to the current api which allow to navigate everywhere and could result in a lot of "prompting" for the user.

Perhaps I'm being unclear in the spec/explainer, but what you're describing is actually exactly what is intended. Calling `chooseFileSystemEntries` with type `openFile` or `saveFile` only gives you access to that single file (and a virtual directory containing only that single file), while calling it with `openDirectory` gives you access to one particular directory with everything it contains (i.e. what you call a 'fs').

I'm not sure if I want to give the website any control over the path it is opening though. Not sure what the use cases are for that, and it seems like it would make it way too easy for a user to just grant it access to whatever it is asking for without thinking about the consequences. Forcing the user to explicitly pick some path at least hopefully makes it slightly less likely that the user just blindly gives access to whatever.

Otherwise what you're describing sounds pretty reasonable/close to what at least in my mind the API looks like.

> Personally, I consider that the developer wants to be sure than all the capabilities he needs will be accepted by the user when requesting the access of a file-system (here directory and its sub-directories), to avoid "half done" work (ex: I created a file A, but the user refused to create file B => my app is in an inconsistent state => crash).

Not entirely sure what you're describing here. At least in my mind this API should not be used to store state for the app. I.e. the explicit purpose of this API is to allow an app to manipulate data for the user, not for the app (yes, there is the sandboxed file system for app state, but there I don't expect we'll have any permission prompts anyway, just like other existing sandboxed storage mechanisms don't have permission prompts). So apps should always be able to deal with things being denied/revoked/modified from out under them, since the exact purpose of this API is to let the user let other apps/websites work with the same files.

**Comment by lifaon74** [comment]
> I'm not sure if I want to give the website any control over the path it is opening though. Not sure what the use cases are for that, and it seems like it would make it way too easy for a user to just grant it access to whatever it is asking for without thinking about the consequences. Forcing the user to explicitly pick some path at least hopefully makes it slightly less likely that the user just blindly gives access to whatever.
Its not forcing its suggesting. Imagine its an app which edit images, It could be great to propose to open the 'Images' folder directly. There is plenty of examples where developers could "propose" a path. Another one could be a minecraft texture editor which could open directly the minecraft folder.

> Not entirely sure what you're describing here. At least in my mind this API should not be used to store state for the app. I.e. the explicit purpose of this API is to allow an app to manipulate data for the user, not for the app (yes, there is the sandboxed file system for app state, but there I don't expect we'll have any permission prompts anyway, just like other existing sandboxed storage mechanisms don't have permission prompts). So apps should always be able to deal with things being denied/revoked/modified from out under them, since the exact purpose of this API is to let the user let other apps/websites work with the same files.
The purporse to ask directly for all the capabilities is:
1) Do not prompt user many times (1st time when requesting reading, 2nd when requesting writing, ...)
2) Show in one popup what the app require to work and accept/reject in one click. VS discovering after 10min of edit than the app requires write and I dont want to grant it... (lost time + poor experience for the user)
3) Notify the developer than all the functionalities of the app will works at the beginning. The purpose is not to save state, but for a big synchronisation of files (ex: dropbox) this could be great not to block the  operation (ex: 10h) after 1h because of a permission popup when the user is not in front of the screen.
(ex: I need to sync files, it will take 10h. My app read files one by one ["read access granted by popup"], I go for a nap. 1h later, the app detect a change, and do a write ["write popup displayed"], but i'm still napping => sync is blocked...)

**Comment by a-sully** [comment]
In general, platforms are moving away from up-front permission requests, towards requesting specific permissions as they're needed at runtime. I don't see us supporting this. 

> Imagine its an app which edit images, It could be great to propose to open the 'Images' folder directly. There is plenty of examples where developers could "propose" a path. Another one could be a minecraft texture editor which could open directly the minecraft folder.

Acquiring a handle from an absolute file path has been proposed in various forms in other issues (such as #301) and is not something we plan to support. If you want to open/save to a specific directory, you can use the `startIn` parameter

> 1. Do not prompt user many times (1st time when requesting reading, 2nd when requesting writing, ...)

We've since removed the double-prompting when asking for a directory with write access (see #300)

> 2. Show in one popup what the app require to work and accept/reject in one click. VS discovering after 10min of edit than the app requires write and I dont want to grant it... (lost time + poor experience for the user)

This will be improved dramatically when Persistent Permissions are launched. Subscribe to #297 and stay tuned :)

> 3. Notify the developer than all the functionalities of the app will works at the beginning. The purpose is not to save state, but for a big synchronisation of files (ex: dropbox) this could be great not to block the  operation (ex: 10h) after 1h because of a permission popup when the user is not in front of the screen.
>    (ex: I need to sync files, it will take 10h. My app read files one by one ["read access granted by popup"], I go for a nap. 1h later, the app detect a change, and do a write ["write popup displayed"], but i'm still napping => sync is blocked...)

Realistically, the browser can _never_ make this guarantee. The user can clear site data at any time, or go into their file manager and remove some of the files the site it operating on.

Also note that children inherit permissions from their parents, so even if you're doing an expensive operation touching all the files in a directory, calling `queryPermission()` on just the root should be enough

**Comment by a-sully** [comment]
Closing this issue, but please re-open or file a new issue if there's something here I missed
