### ISSUE TITLE
Ignoring directories containing tilde character ~

### ISSUE THREAD

**Issue by kepta** [WICG/file-system-access#353]
It is a common practice for users to have `~` in their file name, but it looks like the browser ignores such entries. I could not find anything in spec which forbids this, other than a possible security measure.

**Comment by a-sully** [comment]
Yeah this is quite annoying (and annoyingly difficult to change). The TLDR is that there's a Chromium library this API uses to check "is this file safe" and that library bans tildes because [it's the easiest way to deal with VFAT short names](https://crbug.com/1336156#c19)

Closing this issue since it's a problem with the Chromium implementation rather than the spec. Please continue this discussion on https://crbug.com/1336156
