### ISSUE TITLE
Allow files with no extensions

### ISSUE THREAD

**Issue by sbaechler** [WICG/file-system-access#406]
Currently, the spec [disallows](https://wicg.github.io/file-system-access/#valid-suffix-code-point) file without an extensions. 

There are use-cases where the type of a file is known and the (legacy) software that exported it did not use extensions.

**Comment by a-sully** [comment]
The text

**Comment by a-sully** [comment]
Extensions are not required. See https://fs.spec.whatwg.org/#valid-file-name - although that definition is quite poor and likely to change soon, so follow along on https://github.com/whatwg/fs/issues/93 to see where this is probably heading

The text you linked is just for the file picker options. Meaning you can't specify "only give me files that don't have an extension"... which seems like a niche use case and not something I'd expect platform picker APIs (which generally filter by MIME type) to support anyways

Using [`excludeAcceptAllOption: false`](https://wicg.github.io/file-system-access/#ref-for-dom-filepickeroptions-excludeacceptalloption) (which is the default) you should still be able to select files without an extension, and for the "save" file picker passing a [`suggestedName`](https://wicg.github.io/file-system-access/#dom-savefilepickeroptions-suggestedname) without an extension should work just fine

**Comment by sbaechler** [comment]
The use-case is the file-picker.

Currently it is only possible to allow files with file-endings or all files. But in our case a file has either a .xml ending or no ending. However, .png and .pdf should still not be allowed.

Here is an example of the configuration on [mdn](https://developer.mozilla.org/en-US/docs/Web/API/window/showOpenFilePicker#examples):

```javascript
const pickerOpts = {
  types: [
    {
      description: "Images",
      accept: {
        "image/*": [".png", ".gif", ".jpeg", ".jpg"],
      },
    },
  ],
  excludeAcceptAllOption: true,
  multiple: false,
};
```

An option would be to support an empty string for a given mime-type. The system file picker could then allow files without file endings while still disable those with the wrong file ending.

```javascript
const pickerOpts = {
  types: [
    {
      description: "SEPA Payment Files",
      accept: {
        "text/xml": [".xml", ".pain.001", ""],
      },
    },
  ],
  excludeAcceptAllOption: true,
  multiple: false,
};
```

**Comment by a-sully** [comment]
> Meaning you can't specify "only give me files that don't have an extension"... which seems like a niche use case and not something I'd expect platform picker APIs (which generally filter by MIME type) to support anyways

I looked into this out of curiosity, but this does not seem to be something the underlying platforms support anyways. For example on Mac, [NSOpenPanel](https://developer.apple.com/documentation/appkit/nsopenpanel) takes an [allowedContentTypes](https://developer.apple.com/documentation/appkit/nssavepanel/3566857-allowedcontenttypes) array, which takes a [UTType](https://developer.apple.com/documentation/uniformtypeidentifiers/uttypereference) that doesn't appear to be able to express "files with no type". Things look [similarly not possible on Windows](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.filedialog.filter?view=windowsdesktop-7.0#system-windows-forms-filedialog-filter)

I think `excludeAcceptAllOption: true` is your best bet, and you can always show another picker if the user selects a file of a type you don't support - which you'd need to do anyways, since extension-less files could be of any type. The user could just as easily select an extension-less file that's _not_ a "SEPA Payment File" as they could select a PNG or anything else
