### ISSUE TITLE
Closing Writable is Slow If Content Contains Certain Character Sequence

### ISSUE THREAD

**Issue by tmpmachine** [WICG/file-system-access#434]
Saving file content with certain character sequence such as `<htmlscript>` is twice as slow than without.

```js
async function writeFile(fileHandle, contents) {
  const writable = await fileHandle.createWritable();
  await writable.write('<htmlscript>'); // 2-3x times slower than without when closing

  let then = new Date();

  await writable.close();

  let now = new Date();

  let elapsed = new Date(now - then).getTime();
  console.log(elapsed);
}
```

Test cases ;
- `htmlscript` : fast
- `<htmlscript>` : slow
- `<html Whatever Character Between script>` : slow
- `html Whatever Character Between script` : fast
- `for example <if html script> slow>` : fast
- `for example if< html script> slow>` : slow
- `for example <if html script> slow> < html  > ` : slow
- `for example <if html script> slow> < script > ` : fast
- `for example script>  <html>` : slow
- `for example <html>  <script` : fast
- `for example <html>  script>` : slow

Tested on blank project as well as File System Access API demo : https://googlechromelabs.github.io/text-editor/.

Tested on OS :
- Win 10, Chrome 120 : issue persist
- ChromeOS 119 : no issue

Changing the MIME type on file picker options also has no effect on this issue :

```js
async function getNewFileHandle() {
  const options = {
    /*
    types: [
      {
        description: 'Text Files',
        accept: {
          'text/html': ['.html'],
        },
      },
    ],
    // */
  };
  let handle = await window.showSaveFilePicker(options);
  return handle;
}
```

**Comment by a-sully** [comment]
This discrepancy is likely due to Safe Browsing checks. You could test this by [turning them off](https://support.google.com/chrome/answer/9890866) or writing to a file in the [OPFS](https://developer.mozilla.org/en-US/docs/Web/API/File_System_API/Origin_private_file_system) (for which Safe Browsing checks are not run)

Closing this issue because this is a question about the Chromium implementation. If there's more to this, please [file a Chromium bug](crbug.com/new) under the _Blink>Storage>FileSystem_ component
