### ISSUE TITLE
Double permission prompt when picking folder to write to

### ISSUE THREAD

**Issue by AshleyScirra** [WICG/file-system-access#89]
In Chrome, if you call `window.chooseFileSystemEntries({ type: "openDirectory" })` and immediately write to the directory, the user gets a double permission prompt: first to approve "view files", and then secondly to "save changes". Writing to a chosen folder is typical usage if the app saves a folder-based user project, or needs to export multiple files.

The spec seems to make the assumption that "openDirectory" corresponds to read-only permission, so makes a permission prompt about read access. Then the first attempt to write shows a second permission prompt for write access. Ideally these could be merged in to a single prompt asking the user if they are happy for both read and write access to the folder. There doesn't seem to be a way in the spec to show the intent "open this directory for write access" though. Perhaps one should be added?

**Comment by mkruisselbrink** [comment]
Sort of related to https://crbug.com/998074 as well. Yes, having a "open this directory for write access" is something worth exploring.

**Comment by emarc** [comment]
We're participating in the Chrome Origin Trial, and have been trying the API out.

In short, I think the API should support asking for read+write without causing two dialogs. 

Separate dialogs make sense when different permissions are required as a result of separate actions that the user invokes, especially if the actions are optional.
But for many cases it will be immediately obvious that the application will require both read and write permissions to function. You might have to build strange user flows so that it makes sense for the user that a second popup appears, and you might have to do this in multiple places.

Ultimately the permission dialog is responsible for making the user aware of which permissions they are granting. Asking for read and write with separate dialogs does not automatically make this more clear to the user, but might instead cause “dialog desensitization” – the user is more likely to dismiss the second dialog without thought.

A longer writeup is available here: https://vaadin.com/blog/accessing-files-from-the-browser-with-the-native-file-system-api (scroll down for the actual findings)
The experiment using the API can be found here: https://vaadin.com/labs/native-fs

**Comment by mkruisselbrink** [comment]
Also related to #33. We still definitely want to do this, probably won't make it in the initially shipped version, so bumping this to V2 for now.

**Comment by a-sully** [comment]
[This shipped in Chrome 105](https://chromestatus.com/feature/6383970247770112?context=myfeatures) 

`showDirectoryPicker({ mode: "readwrite" })`
